[package]
name = "pi-gpio-readout"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
anyhow = "1"
rppal = "0.13.1"

[dependencies.clap]
version = "3.2.17"
features = ["derive"]